---
# tasks file for common

- name:
  dnf:
    name: "*"
    state: latest
    update_cache: true

- name:
  dnf:
    name: '{{ item }}'
    state: latest
  loop: '{{ packages }}'

- name: Set hostname '{{ hostname }}'
  hostname:
    name: '{{ hostname }}'

- name: Add user
  user:
    name: '{{ user }}'
    groups:
      - wheel
    home: '/home/{{ user }}'
    shell: /bin/zsh
    append: yes
    state: present

- name: 'Add authorized key file for {{ user }}'
  ansible.posix.authorized_key:
    user: '{{ user }}'
    key: '{{ user_key_url }}'
    state: present
